insert into city_code_tbl_02 values('10', '서울', sysdate);
insert into city_code_tbl_02 values('20', '대전', sysdate);
insert into city_code_tbl_02 values('30', '대구', sysdate);
insert into city_code_tbl_02 values('40', '광주', sysdate);
insert into city_code_tbl_02 values('50', '성남', sysdate);
insert into city_code_tbl_02 values('60', '수원', sysdate);
insert into city_code_tbl_02 values('70', '분당', sysdate);
insert into city_code_tbl_02 values('80', '용인', sysdate);
insert into city_code_tbl_02 values('90', '과천', sysdate);
